name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 167.235.207.71
          username: gituser
          password: ${{ secrets.NETFLUZ_GITUSER_PASSWORD }}
          script: |
            cd /scripts/sponsorManager/
            git pull origin dev
            # Additional deployment steps
